name: deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setups Python
        uses: actions/setup-python@v2
      - name: Run Pre-Commit
        uses: pre-commit/action@v2.0.0
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setups Python
        uses: actions/setup-python@v2
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v4
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
